name: Repository Dispatch
on:
  repository_dispatch:
    types: [doc_update]
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running repository dispatch :) ============================== '